### PR TITLE
Add an optional header to opt out of Google FLoC

### PR DESCRIPTION
**Pull request by quietsy**
Google Federated Learning of Cohorts (FLoC) is a new advertising-surveillance initiative that seeks to replace third-party cookies with a new user profiling technique that garners data generated by the browser itself.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-swag/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Benefits of this PR and context:
Giving the option to opt out of google floc.

## How Has This Been Tested?
I've verified that the header works.

## Source / References:

https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea

### CODE REVIEW

**Comment by nemchik** [comment]
This seems like something we can merge, but just to satisfy my curiosity, do you have a link to a reference that documents how this new header works (and that this is what Google respects with regards to floc). I didn't see any reference to the header in the eff link (might have missed it).

**Comment by quietsy** [comment]
> This seems like something we can merge, but just to satisfy my curiosity, do you have a link to a reference that documents how this new header works (and that this is what Google respects with regards to floc). I didn't see any reference to the header in the eff link (might have missed it).

Sure, more details:
https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network
https://plausible.io/blog/google-floc

**Comment by aptalca** [comment]
Looks good to me. Can you add a changelog entry with the general notice about updating confs?

**Comment by quietsy** [comment]
> Looks good to me. Can you add a changelog entry with the general notice about updating confs?

Sure, done.

**Review by nemchik — APPROVED** [review]

**Pull request merged**
