### PR TITLE
add nginx unauthorized in Using fail2ban section

### PR DESCRIPTION
**Pull request by EVOTk**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [ X] I have read the [contributing](https://github.com/linuxserver/docker-swag/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

add nginx unauthorized in Using fail2ban section

### CODE REVIEW

**Comment by quietsy** [comment]
Thanks for the PR, can you also change `readme-vars.yml` accordingly?

**Comment by EVOTk** [comment]
> Thanks for the PR, can you also change `readme-vars.yml` accordingly?

Sorry, I'm not used to doing PR.
It is done.

**Comment by millerthegorilla** [comment]
You need to add an ```unauthorized.log``` to ```/config/log/nginx/```.   It is touched into existence in ```/etc/cont-init.d/50-config```
as per (https://github.com/millerthegorilla/docker-swag/pull/1/commits/5501308aed695ef3880423bef8a3e92529afc65f).
I don't have the time to test today, before I make the pull request here.   Let me know if you want me to submit the PR.

**Review by quietsy — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
