### PR TITLE
Update detection

### PR DESCRIPTION
**Pull request by nemchik**
backwards compatible in case the output reverts

### CODE REVIEW

**Review by Roxedus — COMMENTED** [review]
This seems to be dependent on the entrypoint and name being the same, which currently is the same.

**Comment by nemchik** [comment]
> This seems to be dependent on the entrypoint and name being the same, which currently is the same.

This is true. I don't know if there is a strict requirement in place for these to match. The entrypoint sounds like the better option to use, but the format output change has me cautious about using it.

**Comment by Roxedus** [comment]
I looked a bit into the entrypoint, and it seems plausible it is referencing pypa entrypoints, which probably isnt changing in the future. <https://github.com/certbot/certbot/blob/master/certbot/certbot/_internal/plugins/disco.py#L178>

**Comment by nemchik** [comment]
> I looked a bit into the entrypoint, and it seems plausible it is referencing pypa entrypoints, which probably isnt changing in the future. https://github.com/certbot/certbot/blob/master/certbot/certbot/_internal/plugins/disco.py#L178

that looks very promising.

**Pull request closed without merging**
