### PR TITLE
Add support for standalone DNS validation

### PR DESCRIPTION
**Pull request by mhofer117**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-swag/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

The certbot-dns-standalone plugin will answer dns challenges directly from certbot.
- It is installed into the container like all other dns plugins
- It is enabled by setting the environment variable `DNSPLUGIN=standalone`
- The ini file `root/defaults/dns-conf/standalone.ini` was only added for documentation purpose, it's not required because the standalone dns authentication plugin does not need any credentials
- The `PROPAGATION` environment variable is ignored because there is no propagation time. Once the plugin is launched, the DNS records are available immediately.
- The plugin is launched only during the dns challenge phase. No DNS queries are answered during normal operations.
- The listen addresses and ports supported by certbot-dns-standalone cannot be specified/changed. But this should not be relevant inside the docker context anyway.
- The only requirements are to map the DNS port 53/UDP into the container and setup the required manual DNS entries as described in the specifications at https://github.com/siilike/certbot-dns-standalone/blob/master/README.rst

## Benefits of this PR and context:

- This allows using dns-01 challenges and issuing wildcard certificates DNS provider independent, even if the provider doesn't have an API or certbot plugin.
- You do not need to wait for a new plugin to support your provider.
- You do not need to switch DNS providers or delegate zones to other 3rd parties.
- DNS challenges are completed very fast because there is no need to wait for any propagation times, 
- No credentials are required.
- May solve #160 for some users

## How Has This Been Tested?

The x86 image has been built and ran locally under Debian 10.11.
The following relevant attributes (redacted) were set in the docker-compose file:
```
        ports:
            - "53:53/udp"
        environment:
            - DNSPLUGIN=standalone
            - URL=home.example.com
            - SUBDOMAINS=wildcard
            - EXTRA_DOMAINS=x.example.com,y.example.com
            - VALIDATION=dns
```
The validation was completed within seconds for the basedomain, the wildcard domain and all EXTRA_DOMAINS at the same time.

The following DNS records (redacted) were prepared upfront to enable the standalone dns challenge:
```
; normal entries
home                         IN A        1.2.3.4
*.home                       IN CNAME    home.example.com.
x                            IN CNAME    home.example.com.
y                            IN CNAME    home.example.com.
; additional entries for standalone dns challenge
home-acme                    IN NS       home.example.com.
_acme-challenge.home         IN CNAME    standalone.home-acme.example.com.
_acme-challenge.x            IN CNAME    standalone.home-acme.example.com.
_acme-challenge.y            IN CNAME    standalone.home-acme.example.com.
```
All of the domains (`home.example.com`, `*.home.example.com`, `x.example.com` and `y.example.com`) were validated successfully and included in the certificate.

Existing functionality should not be affected.

## Source / References:

- [certbot-dns-standalone](https://github.com/siilike/certbot-dns-standalone/blob/master/README.rst)
- This procedure is described in the [Let's Encrypt Challenge Types](https://letsencrypt.org/docs/challenge-types/) as "delegate the _acme-challenge subdomain to a validation-specific server or zone".
- More information is available in [this eff blog post](https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation) in the section "Use a "Throwaway" Validation Domain".

### CODE REVIEW

**Review by nemchik — APPROVED** [review]
LGTM

Very nice!

**Comment by mhofer117** [comment]
Is there a reason this could not be merged yet?
Please let me know what's missing or if this is somehow controversial.

**Comment by aptalca** [comment]
No issues. We just need to test it thoroughly and make sure the docs are appropriate. This PR has the potential to create lots of complicated support requests which adds a significant burden to the team. But feature-wise, it looks great.

**Comment by Bonedeadskull** [comment]
Thank you so much for this.

**Pull request merged**
