### PR TITLE
Move maxmind to a new mod

### PR DESCRIPTION
**Pull request by quietsy**
Moved maxmind to a new mod

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [ ] I have read the [contributing](https://github.com/linuxserver/docker-swag/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

### CODE REVIEW

**Review by nemchik — APPROVED** [review]

**Comment by dsm1212** [comment]
My maxmind config errors now using the docker param for the license key, is there some doc that tells me what to here about this breaking change?

**Comment by aptalca** [comment]
Errors how?

**Comment by quietsy** [comment]
This change shouldn't affect existing users, only new users.

**Comment by dsm1212** [comment]
Error is that it Can’t find the license key in the max
I don’t conf file. I can see the license key environment setting I’m sending to docker was removed so the code no longer reads it.

**Comment by aptalca** [comment]
Open a new issue and fill out the template fully

**Comment by dsm1212** [comment]
I can but really I just want to know where to put the key in the new design. That seems like something useful to put here so others can find it.

-Steve

**Comment by dsm1212** [comment]
Ok, I figured it out.  For others:

1. In general, follow these instructions: https://github.com/linuxserver/docker-mods/blob/swag-maxmind/README.md
2. Start with this content as your maxmind.conf as there is not a default one in swag and you need the first section: https://github.com/linuxserver/docker-mods/blob/swag-maxmind/root/defaults/maxmind.conf. Adjust the whitelist/blacklist/lan defintions as you see fit.
3. In your nginx.conf comment/remove the include for geoip2.conf because it is no longer needed.

The maxmind license key env var you had before does not change once you do these steps so leave it in place.

**Pull request merged**
