### PR TITLE
move samples to a separate folder

### PR DESCRIPTION
**Pull request by fariszr**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-swag/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

this PR moves samples to a separate folder called `proxy-confs-samples` and to activate them `.conf` files should be put in the `proxy-confs` folder

**THIS WILL REQUIRE UPDATE TO THE [reverse-proxy-confs](https://github.com/linuxserver/reverse-proxy-confs) README AND LSIO DOCUMENTAION** (sidenote: LSIO documentation doesn't seem to be open source, and there is no way to contribute)

## Benefits of this PR and context:

currently samples and production configs are located in the same folder.
this makes it difficult to find actual config files, because of how much samples are available
separating samples from production configs would make it much easier to find configs used currently 

## How Has This Been Tested?

used the uptime kuma sample, just moved it to proxy-conf and removed the `.sample` extension, and everything worked.

### CODE REVIEW

**Comment by Roxedus** [comment]
Docs.linuxserver.io is sourced from https://github.com/linuxserver/docker-documentation

**Comment by fariszr** [comment]
Great !, if this PR gets merged I will open a PR to update the documentation.

**Comment by nemchik** [comment]
We're discussing internally some changes that might line up with this. Might not merge super quick.

**Comment by fariszr** [comment]
> We're discussing internally some changes that might line up with this. Might not merge super quick.

any plans on multi-cert support(separate Let's encrypt cert for different domains) ?

**Comment by j0nnymoe** [comment]
As discussed in previous issues, no plan to. 
https://github.com/linuxserver/docker-swag/issues/33

**Comment by fariszr** [comment]
> We're discussing internally some changes that might line up with this. Might not merge super quick.

is there any thing holding back #182 ?

**Comment by nemchik** [comment]
> > We're discussing internally some changes that might line up with this. Might not merge super quick.
> 
> is there any thing holding back #182 ?

Review submit on #182

**Comment by drizuid** [comment]
We are going to pass on this PR. We think the added support overhead for this would be something we don't wish to incur (currently, this is a single step process for our users, rename .sample to .conf and it Just works. moving the samples would then require users to copy or move the file to the intended location and rename it. Strictly speaking, this is too much to ask of most of our userbase who are barely capable of reading the readme). We are discussing some other modifications to the current setup internally but it will not look like this. fwiw, just `ls *.conf` to not see the samples.

**Comment by fariszr** [comment]
You don't have to rename the files, make the samples use .conf by default.

Its just a matter of moving the files to another directory.

I don't see how this adds much overhead to new users.

**Pull request closed without merging**
