### PR TITLE
Update 50-config create fail2ban unauthorized.log

### PR DESCRIPTION
**Pull request by millerthegorilla**
added code to test for existence of unauthorized.log and create it if not exists.
/config/log/nginx/unauthorized.log is written to by addition of nginx-unauthorized jail in jail.local

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [ x] I have read the [contributing](https://github.com/linuxserver/docker-swag/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Benefits of this PR and context:

This fixes a bug where the current image complains repeatedly that it is unable to find the file 'unauthorized.log'

## How Has This Been Tested?

image has been built locally.

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks for the PR. Can you add a changelog entry as well, to readme-vars.yml?

**Comment by millerthegorilla** [comment]
I have made a separate pull request to add the changelog.

**Comment by millerthegorilla** [comment]
Ok, I have added the changelog to the file.  Sorry I didn't do it earlier.

**Review by aptalca — APPROVED** [review]
looks good, thanks

**Pull request merged**
